### ISSUE TITLE
Meeting Date

### ISSUE THREAD

**Issue by whereswaldon** [boone-linux-users/meta#1]
I think that Mondays at 6 or 6:30pm works well for me. I'd expect to meet for 2-3 hours. How well does that work for everyone else?

**Comment by stephen-bunn** [comment]
6 on Mondays works fine for me.

**Comment by jordangaston** [comment]
6:30 works better for me, I have capstone until then

**Comment by whereswaldon** [comment]
That 30 minute difference would give me time to acquire food for everyone (hopefully). I'm down for 6:30

**Comment by whereswaldon** [comment]
I think we've essentially settled on 6:30pm, so I'm going to close this one.
