### ISSUE TITLE
Food at meetings?

### ISSUE THREAD

**Issue by whereswaldon** [boone-linux-users/meta#2]
Do you guys want to eat at meetings? If so, what kinds of food options interest people?

**Comment by whereswaldon** [comment]
Just a suggestion: Pizza. It's easy, and there are places where we can get it very cheaply. For instance, someone could run to Little Caesar's and pick up like 5 for $25(plus tax). That would limit us to only Cheese, Pepperoni, or Sausage though.
Any other suggestions?

**Comment by stephen-bunn** [comment]
I would be fine with that. Members could volunteer to rotate runs if we plan on having food for every meeting.

**Comment by whereswaldon** [comment]
Rotation would be pretty nice. For Monday, does anyone have pizza topping preferences (see above for options)?

**Comment by whereswaldon** [comment]
I believe this issue is also settled. We rotate who buys food, and everyone pays whoever bought a few bucks. Sweet and simple.
