### ISSUE TITLE
Saturday Informal Meetup

### ISSUE THREAD

**Issue by whereswaldon** [boone-linux-users/meta#3]
This isn't a structured meeting, but rather a chance for people interested in this group to get to know one another and swap information.

Where: The ASU Library
When: 12:00pm - ?

This would be a great time to install Linux on your computer if you haven't already done that.

**Comment by stephen-bunn** [comment]
Would you like to book a large room for the Saturday meeting?
It might be nice to get a place with a whiteboard and a projector (or large screen) if possible.

**Comment by whereswaldon** [comment]
I have library room 303 from 12pm-6pm. Good idea to reserve one. It's hard to tell how the room is equipped from the library website. We should at least have a whiteboard, computer, and 'large screen' (their words, not mine. Projector?) in the room.

**Comment by stephen-bunn** [comment]
They do have a sort of checklist of room features on the library website. Idk if [this](https://groupstudy.library.appstate.edu/admin.php?day=2&month=2&year=2017&area=3&room=24) link will work for you, but we can probably register a room weekly if we plan on doing things at the same time every week.

But if so, we can maybe get room 210, 243, or 303 which have the largest capacities. The former two don't "large screens" from what I can tell.

**Comment by whereswaldon** [comment]
Thanks to everyone who came! I'm going to close this issue now that the meeting is over.
